sudo: false
language: scala
scala:
  - 2.11.12
jdk:
  - oraclejdk8
branches:
  only:
    - master
script:
  - sbt ++$TRAVIS_SCALA_VERSION check-gen-type-classes test
  - sbt ++$TRAVIS_SCALA_VERSION check-gen-type-classes compile
  - sbt ++$TRAVIS_SCALA_VERSION check-gen-type-classes assembly
# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file:
#     - target/scala-2.11/ot-geckopipe-assembly-*
#   skip_cleanup: true
#   on:
#     tags: true
notifications:
  email:
    recipients:
      - mkarmona@gmail.com
    on_success: never
    on_failure: always
#  slack:
#    rooms:
#      - secure: "sdfusdhfsdofguhdfgubdsifgudfbgs3453durghssebarfooexample="
#    on_success: always